module "ecs" {
  source                                = "../../../ecs_with_sidecar"

  email                                 = var.email
  teamid                                = var.teamid
  prjid                                 = var.prjid
  key_name                              = var.key_name
  aws_region                            = var.aws_region
  account_id                            = var.account_id
  dns_name                              = var.dns_name
  type_of_record                        = var.type_of_record
  iam_instance_profile_to_use           = var.iam_instance_profile_to_use
  profile_to_use                        = var.profile_to_use
  security_groups_to_use                = var.security_groups_to_use
  deploy_route53                        = var.deploy_route53
  inst_type                             = var.inst_type
  family                                = var.family
  task_instance_count                   = var.task_instance_count
  execution_role_arn                    = var.execution_role_arn
  task_role_arn                         = var.task_role_arn
  user_data_file_path                   = var.user_data_file_path
  pid_mode                              = var.pid_mode
  # -----------------------------------------------------------------
  # CONTAINER 1
  # -----------------------------------------------------------------
  volumes                               = var.volumes
  placement_constraints                 = var.placement_constraints
  secrets                               = var.secrets
  privileged                            = var.privileged
  command                               = var.command
  entrypoint                            = var.entrypoint
  environment                           = var.environment
  environment_files                     = var.environment_files
  mount_points                          = var.mount_points
  alb_cert_arn                          = var.alb_cert_arn
  alb_ssl_policy                        = var.alb_ssl_policy
  healthcheck                           = var.healthcheck
  port_mappings                         = var.port_mappings
  memory_reservation                    = var.memory_reservation
  readonly_root_filesystem              = var.readonly_root_filesystem
  essential                             = var.essential
  lb_type                               = var.lb_type
  lb_protocol                           = var.lb_protocol
  healthcheck_path                      = var.healthcheck_path
  healthcheck_matcher                   = var.healthcheck_matcher
  healthcheck_timeout                   = var.healthcheck_timeout
  healthcheck_interval                  = var.healthcheck_interval
  healthy_threshold                     = var.healthy_threshold
  unhealthy_threshold                   = var.unhealthy_threshold
  lb_port                               = var.lb_port
  container_image                       = var.container_image
  container_port                        = var.container_port
  container_memory                      = var.container_memory
  container_cpu                         = var.container_cpu
  task_memory                           = var.task_memory
  task_cpu                              = var.task_cpu
  network_mode                          = var.network_mode
  log_configuration                     = var.log_configuration
  # -----------------------------------------------------------------
  # CONTAINER 2
  # -----------------------------------------------------------------
  container_image_sidecar               = var.container_image_sidecar
  environment_sidecar                   = var.environment_sidecar
  environment_files_sidecar             = var.environment_files_sidecar
  log_configuration_sidecar             = var.log_configuration_sidecar
  readonly_root_filesystem_sidecar      = var.readonly_root_filesystem_sidecar
  container_cpu_sidecar                 = var.container_cpu_sidecar
  container_memory_sidecar              = var.container_memory_sidecar
  task_memory_sidecar                   = var.task_memory_sidecar
  task_cpu_sidecar                      = var.task_cpu_sidecar
  container_port_sidecar                = var.container_port_sidecar
  port_mappings_sidecar                 = var.port_mappings_sidecar
  lb_port_sidecar                       = var.lb_port_sidecar
  lb_protocol_sidecar                   = var.lb_protocol_sidecar
  healthcheck_sidecar                   = var.healthcheck_sidecar
  healthcheck_path_sidecar              = var.healthcheck_path_sidecar
  healthcheck_matcher_sidecar           = var.healthcheck_matcher_sidecar
  healthcheck_timeout_sidecar           = var.healthcheck_timeout_sidecar
  healthcheck_interval_sidecar          = var.healthcheck_interval_sidecar
  healthy_threshold_sidecar             = var.healthy_threshold_sidecar
  unhealthy_threshold_sidecar           = var.unhealthy_threshold_sidecar
  essential_sidecar                     = var.essential_sidecar
  privileged_sidecar                    = var.privileged_sidecar
  network_mode_sidecar                  = var.network_mode_sidecar
}
